#!/usr/bin/env bash
# Provision (idempotently) an isolated frontend instance for this worktree:
# writes a gitignored .env.local with a unique dev port, a backend/DB target
# (default: prod, for zero-setup verification), and the current branch — so
# `npm run dev` runs on its own port and the in-app badge shows branch + DB.
#
# Re-running is safe: an existing port + DB choice are kept; branch/name refresh.
set -eu

PROD_URL="https://medmkp-medusa.onrender.com"
LOCAL_URL="http://127.0.0.1:9000"
PORT_MIN=3001
PORT_MAX=3099

root="$(git rev-parse --show-toplevel)"
envfile="$root/.env.local"
branch="$(git -C "$root" branch --show-current 2>/dev/null || true)"
[ -n "$branch" ] || branch="detached"
wtname="$(basename "$root")"

read_val() { [ -f "$envfile" ] && sed -n "s/^$1=//p" "$envfile" | head -1 || true; }
port="$(read_val MEDMKP_PORT)"
db="$(read_val MEDMKP_DB_TARGET)"

# Allocate a port only if this worktree doesn't already have one.
if [ -z "$port" ]; then
  claimed=" "
  for wt in $(git worktree list --porcelain | awk '/^worktree /{print $2}'); do
    p="$(sed -n 's/^MEDMKP_PORT=//p' "$wt/.env.local" 2>/dev/null | head -1 || true)"
    [ -n "$p" ] && claimed="$claimed$p "
  done
  span=$(( PORT_MAX - PORT_MIN + 1 ))
  # Deterministic start offset from the branch name, then linear-probe upward
  # so the same branch tends to land on the same port across re-creates.
  start=$(( PORT_MIN + ($(printf '%s' "$branch" | cksum | cut -d' ' -f1) % span) ))
  for off in $(seq 0 $((span - 1))); do
    cand=$(( PORT_MIN + ((start - PORT_MIN + off) % span) ))
    case "$claimed" in *" $cand "*) continue ;; esac
    if ! lsof -nP -iTCP:"$cand" -sTCP:LISTEN >/dev/null 2>&1; then port="$cand"; break; fi
  done
  [ -n "$port" ] || { echo "worktree-init: no free port in $PORT_MIN-$PORT_MAX" >&2; exit 1; }
fi

# Default DB target = prod; only honour an explicit existing "local" choice.
case "$db" in
  local) url="$LOCAL_URL" ;;
  *)     db="prod"; url="$PROD_URL" ;;
esac

cat > "$envfile" <<EOF
# Auto-generated by scripts/worktree-init.sh — per-worktree frontend instance.
# Switch DB target with:  npm run wt:local  /  npm run wt:prod
MEDMKP_PORT=$port
MEDMKP_DB_TARGET=$db
MEDUSA_BACKEND_URL=$url
MEDMKP_BRANCH=$branch
MEDMKP_WORKTREE=$wtname
EOF

echo "worktree-init: $wtname → :$port · DB=$db · $branch"
